### ISSUE TITLE
I suggest you could build GDB against python 3.x

### ISSUE THREAD

**Issue by asmwarrior** [ssbssa/gdb#2]
Hi, I just download the file `gdb-11.2.90.20220320-x86_64-python.7z`, and I see it has a `python27.dll`. So, I would suggest using a modern python 3.x version. If I remember correctly, the official GDB will drop the python 2.x support.

Thanks.

**Comment by ssbssa** [comment]
You're right, the upcoming gdb version 12 will be the last one with python 2 support.
Coincidentally, a short while before they announced this, I actually started playing with python 3, building it myself, etc...
So my next build will use python 3, statically linked, and it should be available a short while after the official version 12 release.

**Comment by ssbssa** [comment]
Done now with https://github.com/ssbssa/gdb/releases/tag/gdb-12.1.90.20220502.

**Comment by asmwarrior** [comment]
Hi, ssbssa, thanks.

I will download it and test it.

BTW: do you have any wiki or other document about how to build your gdb?
Do you use github action? Or you just build it in your local PC?
Thanks.

**Comment by ssbssa** [comment]
> BTW: do you have any wiki or other document about how to build your gdb?

I have a Makefile which contains all the build steps, but I haven't shared it (yet).
Don't know where I would put it.

> Do you use github action? Or you just build it in your local PC?

On my local PC.

**Comment by asmwarrior** [comment]
I think you can put the code in a wiki page.

I did similar things several years ago when I build 32bit GDB from time to time in MinGW's msys(that the version 1 of msys), see my old steps here: https://sourceforge.net/p/gdbmingw/wiki/Build%20GDB%20under%20MSYS/

**Comment by ssbssa** [comment]
> I think you can put the code in a wiki page.

A bit late, but I've now put all my build related stuff here into the [build](https://github.com/ssbssa/gdb/tree/build) branch.
To actually use it you would have to put the source packages/repositories into specific folders, but at least you can now check out all my source code changes.

**Comment by asmwarrior** [comment]
Thanks. Since building gdb is not an easy task,  I haven't done it for several years.  I just use your release right now,  Thank you for sharing.
