### ISSUE TITLE
Crash on 'info locals'

### ISSUE THREAD

**Issue by overloader7** [ssbssa/gdb#3]
I don't know where i should put this, but gdb crashes on 'info locals' when trying to read bad(null and nearby) char pointers in the latest release. The previous release works fine. Using Windows 7, so that might have something to do with newer versions of python not being supported on it (although everything else seems to work fine).

**Comment by ssbssa** [comment]
I also test on Windows 7, so that shouldn't be the problem.
Can you maybe create a small reproducer for me, because I don't think that I've had this problem.

**Comment by ssbssa** [comment]
You may also want to try the upcoming gdb-13 version, maybe this was already fixed.
I've put a test build here (compressed twice, because for some reason github doesn't like 7z files): [gdb64-python_2.zip](https://github.com/ssbssa/gdb/files/10420166/gdb64-python_2.zip)

**Comment by overloader7** [comment]
This gdb-13 build indeed works fine, so it was probably fixed. 

But just in case it matters, just a declared `WNDCLASSEX` variable from `windows.h`, compiled with `-m64 -ggdb3 -O0`, gcc version `12.2.0 (x86-64-win32-seh-rev2)` in gdb 12.1.90.20220502-git, commands `start`, `info locals`, it writes things up to `hbrBackground` (after it should come a const char* value) and crashes.
