### ISSUE TITLE
why is this not upstream?

### ISSUE THREAD

**Issue by Kreijstal** [ssbssa/gdb#5]
It sure seems useful?

**Comment by ssbssa** [comment]
What exactly do you mean?

**Comment by Kreijstal** [comment]
like why is this not included in the original gdb codebase.
As in, would it be possible to put this code in the original gdb codebase if not, how do you keep this up to date?

**Comment by ssbssa** [comment]
I actually do try to upstream as much as possible, starting with the bugfixes (there are currently 4 of them waiting for review).
New features are harder to upstream, they need a lot of patience, and often many rounds of revisions.

As for how I keep it up to date, whenever a new release branch is created, I rebase all my patches above them.
It's a lot of work, but like this I have to do it at most twice a year, so it's doable.

**Comment by ssbssa** [comment]
I guess this answers it, so I'm closing this.
Feel free to reopen if you have more questions.
