### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by johannesthoma** [ssbssa/gdb#6]
Hello Hannes,

First a big thank you for hacking on Windows minidump file support.

I tried to compile your gdb by myself (before I discovered that you also
provide pre-compiled 7z archives) and have some questions:

1.) I am using a x86_64-pc-cygwin gcc compiler to build gdb (the one
that comes with cygwin). There were some minor issues, most of them
could be fixed (see
https://github.com/johannesthoma/gdb-from-ssbssa/tree/jt/cygwin-compile-fixes
) but I am not sure if this is even the right compiler to use (it didn't work at
all with the mingw compiler which is probably expected since gdb relies
on some POSIX functionality). So the question would be if you are also
building with the cygwin compiler or if you are using something else.

2.) The resulting gdb crashes when opening a cygwin compiled EXE: here is
the output:

Recursive internal problem.
cp-name-parser.y:192: internal-error: fill_comp: Assertion `i' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
----- Backtrace -----

Fatal signal: Aborted
----- Backtrace -----

Again I would assume some build error (wrong compiler, ...) since the
binary version you provided works with the exe (it can even parse the
minidump file I got from the client). 

Thanks again for your hard work on teaching minidump to gdb I think
that is the direction it should go. I assume (and will later try) it would
also support minidump files from BSODs, right?

Best regards,

- Johannes

**Comment by ssbssa** [comment]
> 1.) I am using a x86_64-pc-cygwin gcc compiler to build gdb (the one that comes with cygwin). There were some minor issues, most of them could be fixed (see https://github.com/johannesthoma/gdb-from-ssbssa/tree/jt/cygwin-compile-fixes ) but I am not sure if this is even the right compiler to use (it didn't work at all with the mingw compiler which is probably expected since gdb relies on some POSIX functionality). So the question would be if you are also building with the cygwin compiler or if you are using something else.

I'm using a mingw-w64 gcc which I compiled myself with MSYS2, but I would expect that it works with any of the cygwin or MSYS2 provided compilers as well.

> 2.) The resulting gdb crashes when opening a cygwin compiled EXE: here is the output:
> 
> Recursive internal problem. cp-name-parser.y:192: internal-error: fill_comp: Assertion `i' failed. A problem internal to GDB has been detected, further debugging may prove unreliable. ----- Backtrace -----
> 
> Fatal signal: Aborted ----- Backtrace -----
> 
> Again I would assume some build error (wrong compiler, ...) since the binary version you provided works with the exe (it can even parse the minidump file I got from the client).

I made one change to cp-name-parser.y which might be the problem: https://github.com/ssbssa/gdb/commit/718f1577b8ff4da2794bfdc20563e77d86d4f39e
You could try to revert this for you build and see if it works then.

> Thanks again for your hard work on teaching minidump to gdb I think that is the direction it should go. I assume (and will later try) it would also support minidump files from BSODs, right?

Good question about BSOD minidumps, I have no idea if they work, never tried to debug one myself.

**Comment by johannesthoma** [comment]
Hi,

Thanks for the fast answer.

I tried to revert the 718f1577b8ff commit you mentioned but it didn't make
any difference. Maybe the different compiler (cygwin instead of mingw64)
is the problem. I could not get it compile with the i686-w64-mingw compiler
I will try now with the x86_64-mingw..

**Comment by ssbssa** [comment]
> I tried to revert the [718f157](https://github.com/ssbssa/gdb/commit/718f1577b8ff4da2794bfdc20563e77d86d4f39e) commit you mentioned but it didn't make any difference. Maybe the different compiler (cygwin instead of mingw64) is the problem. I could not get it compile with the i686-w64-mingw compiler I will try now with the x86_64-mingw..

What's the problem you have when compiling with the i686-w64-mingw compiler?

**Comment by johannesthoma** [comment]
Hi, I retried with

`
./configure CC=x86_64-w64-mingw32-gcc --host=x86_64-w64-mingw32`

and this time it worked. After doing:

```
make -j 8 -k
make -j 8 -k install
```
(note that -j 8 -k is optional)
and adding the mingw's bin directory to the $PATH: as in:

`
PATH=$PATH:/cygdrive/c/cygwin64/usr/x86_64-w64-mingw32/sys-root/mingw/bin`

I got a gdb that can debug cygwin compiled programs. Probably the problem
before was is that I did not specify the `--host=x86_64-w64-mingw32` (or whatever
other compiler I tried) which seems to confuse the build process.

**Comment by johannesthoma** [comment]
The problem before was when configuring as:

`./configure CC=i686-w64-mingw32-gcc`

I got errors like:

```
i686-w64-mingw32-gcc -c -DHAVE_CONFIG_H -g -O2      -I. -I./../include  -W -Wall -Wwrite-strings -Wc++-compat -Wstrict-prototypes -Wshadow=local -pedantic  -D_GNU_SOURCE  ./pex-unix.c -o pex-unix.o
./pex-unix.c: In function ‘pex_wait’:
./pex-unix.c:256:14: warning: implicit declaration of function ‘wait’; did you mean ‘cwait’? [-Wimplicit-function-declaration]
  256 |       cpid = wait (status);
      |              ^~~~
      |              cwait
./pex-unix.c: In function ‘save_and_install_fd’:
./pex-unix.c:382:11: warning: implicit declaration of function ‘fcntl’ [-Wimplicit-function-declaration]
  382 |   flags = fcntl (old_fd, F_GETFD);
      |           ^~~~~
./pex-unix.c:382:26: error: ‘F_GETFD’ undeclared (first use in this function)
  382 |   flags = fcntl (old_fd, F_GETFD);
      |                          ^~~~~~~
./pex-unix.c:382:26: note: each undeclared identifier is reported only once for each function it appears in
./pex-unix.c:395:20: error: ‘FD_CLOEXEC’ undeclared (first use in this function)
  395 |       if ((flags & FD_CLOEXEC) == 0 && fcntl (old_fd, F_SETFD, FD_CLOEXEC) < 0)
      |                    ^~~~~~~~~~
./pex-unix.c:395:55: error: ‘F_SETFD’ undeclared (first use in this function)
  395 |       if ((flags & FD_CLOEXEC) == 0 && fcntl (old_fd, F_SETFD, FD_CLOEXEC) < 0)
      |                                                       ^~~~~~~
./pex-unix.c:408:31: error: ‘F_DUPFD’ undeclared (first use in this function)
  408 |       new_fd = fcntl (old_fd, F_DUPFD, 3);
      |                               ^~~~~~~
./pex-unix.c: In function ‘restore_fd’:
./pex-unix.c:442:19: error: ‘FD_CLOEXEC’ undeclared (first use in this function)
  442 |       if (flags & FD_CLOEXEC)
      |                   ^~~~~~~~~~
./pex-unix.c:444:29: error: ‘F_SETFD’ undeclared (first use in this function)
  444 |       return fcntl (old_fd, F_SETFD, flags);
      |                             ^~~~~~~
./pex-unix.c: In function ‘pex_unix_exec_child’:
./pex-unix.c:526:49: warning: passing argument 3 of ‘spawnvpe’ from incompatible pointer type [-Wincompatible-pointer-types]
  526 |         pid = spawnvpe (_P_NOWAITO, executable, (cc_cp)argv, (cc_cp)env);
      |                                                 ^~~~~~~~~~~
      |                                                 |
      |                                                 const char * const*
In file included from /usr/i686-w64-mingw32/sys-root/mingw/include/unistd.h:11,
                 from ./pex-unix.c:40:
/usr/i686-w64-mingw32/sys-root/mingw/include/process.h:199:75: note: expected ‘char * const*’ but argument is of type ‘const char * const*’
  199 |   _CRTIMP intptr_t __cdecl spawnvpe(int,const char *_Filename,char *const _ArgList[],char *const _Env[]) __MINGW_ATTRIB_DEPRECATED_MSVC2005;
      |                                                               ~~~~~~~~~~~~^~~~~~~~~~
./pex-unix.c:526:62: warning: passing argument 4 of ‘spawnvpe’ from incompatible pointer type [-Wincompatible-pointer-types]
  526 |         pid = spawnvpe (_P_NOWAITO, executable, (cc_cp)argv, (cc_cp)env);
      |                                                              ^~~~~~~~~~
      |                                                              |
      |                                                              const char * const*
In file included from /usr/i686-w64-mingw32/sys-root/mingw/include/unistd.h:11,
                 from ./pex-unix.c:40:
/usr/i686-w64-mingw32/sys-root/mingw/include/process.h:199:98: note: expected ‘char * const*’ but argument is of type ‘const char * const*’
  199 |   _CRTIMP intptr_t __cdecl spawnvpe(int,const char *_Filename,char *const _ArgList[],char *const _Env[]) __MINGW_ATTRIB_DEPRECATED_MSVC2005;
      |                                                                                      ~~~~~~~~~~~~^~~~~~
./pex-unix.c:528:48: warning: passing argument 3 of ‘spawnve’ from incompatible pointer type [-Wincompatible-pointer-types]
  528 |         pid = spawnve (_P_NOWAITO, executable, (cc_cp)argv, (cc_cp)env);
      |                                                ^~~~~~~~~~~
      |                                                |
      |                                                const char * const*
In file included from /usr/i686-w64-mingw32/sys-root/mingw/include/unistd.h:11,
                 from ./pex-unix.c:40:
/usr/i686-w64-mingw32/sys-root/mingw/include/process.h:197:74: note: expected ‘char * const*’ but argument is of type ‘const char * const*’
  197 |   _CRTIMP intptr_t __cdecl spawnve(int,const char *_Filename,char *const _ArgList[],char *const _Env[]) __MINGW_ATTRIB_DEPRECATED_MSVC2005;
      |                                                              ~~~~~~~~~~~~^~~~~~~~~~
./pex-unix.c:528:61: warning: passing argument 4 of ‘spawnve’ from incompatible pointer type [-Wincompatible-pointer-types]
  528 |         pid = spawnve (_P_NOWAITO, executable, (cc_cp)argv, (cc_cp)env);
      |                                                             ^~~~~~~~~~
      |                                                             |
      |                                                             const char * const*
In file included from /usr/i686-w64-mingw32/sys-root/mingw/include/unistd.h:11,
                 from ./pex-unix.c:40:
/usr/i686-w64-mingw32/sys-root/mingw/include/process.h:197:97: note: expected ‘char * const*’ but argument is of type ‘const char * const*’
  197 |   _CRTIMP intptr_t __cdecl spawnve(int,const char *_Filename,char *const _ArgList[],char *const _Env[]) __MINGW_ATTRIB_DEPRECATED_MSVC2005;
      |                                                                                     ~~~~~~~~~~~~^~~~~~
./pex-unix.c: In function ‘pex_unix_wait’:
./pex-unix.c:777:5: warning: implicit declaration of function ‘kill’ [-Wimplicit-function-declaration]
  777 |     kill (pid, SIGTERM);
      |     ^~~~
./pex-unix.c: In function ‘pex_unix_pipe’:
./pex-unix.c:795:10: warning: implicit declaration of function ‘pipe’; did you mean ‘_pipe’? [-Wimplicit-function-declaration]
  795 |   return pipe (p);
      |          ^~~~
      |          _pipe
./pex-unix.c: In function ‘pex_unix_fdopenw’:
./pex-unix.c:811:18: error: ‘F_SETFD’ undeclared (first use in this function)
  811 |   if (fcntl (fd, F_SETFD, FD_CLOEXEC) < 0)
      |                  ^~~~~~~
./pex-unix.c:811:27: error: ‘FD_CLOEXEC’ undeclared (first use in this function)
  811 |   if (fcntl (fd, F_SETFD, FD_CLOEXEC) < 0)
      |                           ^~~~~~~~~~
./pex-unix.c: In function ‘pex_unix_cleanup’:
./pex-unix.c:822:27: warning: identifier ‘this’ conflicts with C++ keyword [-Wc++-compat]
  822 |       struct status_list *this;
      |                           ^~~~
./pex-unix.c:825:7: warning: identifier ‘this’ conflicts with C++ keyword [-Wc++-compat]
  825 |       this = (struct status_list *) obj->sysdep;
      |       ^~~~
./pex-unix.c:826:14: warning: identifier ‘this’ conflicts with C++ keyword [-Wc++-compat]
  826 |       next = this->next;
      |              ^~~~
./pex-unix.c:827:13: warning: identifier ‘this’ conflicts with C++ keyword [-Wc++-compat]
  827 |       free (this);
      |             ^~~~

```

probably because I didn't specify `--host=i686-w64-mingw32`

I will try this and check if the compiler errors are fixed.

**Comment by ssbssa** [comment]
> probably because I didn't specify `--host=i686-w64-mingw32`

Yes, I also think that this was probably the issue (I always specify build/host when compiling gdb).

**Comment by johannesthoma** [comment]
Hi configuring with

`./configure --host=i686-w64-mingw32`

and building the 'normal' way (`make && make install`) worked now. I am also trying again
with the cygwin compiler now.

Would you maybe share your config options you are using to create the binaries? For example,
you seem to have tui enabled which is disabled by default.

**Comment by ssbssa** [comment]
Sure I can share it:

`configure --build=i686-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --enable-static --disable-shared --disable-nls --enable-curses --enable-tui --with-libiconv-prefix=/gdb/gdb-libs64 --with-liblzma-prefix=/gdb/gdb-libs64 --with-xxhash --disable-install-libbfd --disable-install-libiberty --disable-binutils --disable-gas --disable-gprof --disable-ld --disable-sim --with-system-gdbinit=/gdb/gdb64-git-python3/etc/gdbinit --with-system-gdbinit-dir=/gdb/gdb64-git-python3/etc/gdbinit.d --with-pkgversion=ssbssa-1 --prefix=/gdb/gdb64-git-python3 --with-python=/gdb/gdb-libs64/Python3/bin/python3 --with-python-libdir=/gdb/gdb64-git-python3/lib --enable-targets=all`

But I doubt it will be helpful to you, since I built all the dependencies myself.

**Comment by johannesthoma** [comment]
Hi thanks for sharing the config ... I now tried to compile with:

`./configure --host=x86_64-pc-cygwin`

and it failed. If you wish I can improve the patches in my 
https://github.com/johannesthoma/gdb-from-ssbssa/tree/jt/cygwin-compile-fixes
jt/cygwin-compile-fixes branch (I would at least test if they don't break the
mingw builds) but probably for supporting the cygwin compiler it needs a little bit
more than that (right now testing if the internal error mentioned above still exists).

**Comment by johannesthoma** [comment]
Hi, unfortunately building with the cygwin gcc (x86_64-pc-cygwin) does
not work at the moment (mingw works). Since my questions are answered
we can close this issue, thanks again for your help!

**Comment by ssbssa** [comment]
The [new 14.2 tag](https://github.com/ssbssa/gdb/releases/tag/gdb-14.2.90.20240515) should build without changes for cygwin as well.

**Comment by johannesthoma** [comment]
Hi thanks for providing this release. I cloned it (git hash is 2dbed792fa70efbdd)
and configured gdb without parameters:

    ./configure

Then I started building with:

    make -j 8 

after a while the build process stopped with:

      CCLD     as-new.exe
    /usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: ../bfd/.libs/libbfd.a: error adding symbols: archive has no index; run ranlib to add one
    collect2: error: ld returned 1 exit status
    make[4]: *** [Makefile:1295: as-new.exe] Error 1
    make[4]: Leaving directory '/home/Administrator/gdb-may-2024/gdb/gas'
    make[3]: *** [Makefile:1674: all-recursive] Error 1
    make[3]: Leaving directory '/home/Administrator/gdb-may-2024/gdb/gas'
    make[2]: *** [Makefile:1014: all] Error 2
    make[2]: Leaving directory '/home/Administrator/gdb-may-2024/gdb/gas'
    make[1]: *** [Makefile:5472: all-gas] Error 2
    make[1]: Leaving directory '/home/Administrator/gdb-may-2024/gdb'
    make: *** [Makefile:1024: all] Error 2

Build system is a recent cygwin running on Windows Server 2019, should that work?
The ranlib command is installed and also detected by the configure logic.

Not sure if I did something wrong. Can you reproduce this issue on your system?

Best regards and thanks a lot again :)

- Johannes

**Comment by ssbssa** [comment]
Do you need binutils/gas/...?
Because when building gdb I always have this stuff disabled with: `--disable-binutils --disable-gas --disable-gprof --disable-ld --disable-sim`

**Comment by johannesthoma** [comment]
Hi Hannes,

I keep getting ranlib related errors:

      CXXLD  gdb.exe
    /usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: ../readline/readline/libreadline.a: error adding symbols: archive has no index; run ranlib to add one

It must be something with my cygwin installation. Did you see this error before?

I configured with:

    ./configure --build=x86_64-pc-cygwin --host=x86_64-pc-cygwin --target=x86_64-pc-cygwin --enable-static --disable-shared --disable-nls --enable-curses --disable-install-libbfd --disable-install-libiberty --disable-binutils --disable-gas --disable-gprof --disable-ld --disable-sim --with-pkgversion=ssbssa-1 --enable-targets=all --disable-tui

I will try to cross compile on a Linux machine to check if it is working there.

**Comment by ssbssa** [comment]
No, I've never seen this error before.
And I just tried to compile it again in cygwin, I had no problems at all.
