### ISSUE TITLE
Feature request: support crash dumps (as created by BSOD handlers).

### ISSUE THREAD

**Issue by johannesthoma** [ssbssa/gdb#8]
Hi :)

Regarding the crash dump (result of a BSOD): This file format seems to be something different from minidumps. I'm not sure if the debug helper DLLs should be able to parse them. When I try to open a MEMORY.DMP file it says:

   (gdb) core MEMORY.DMP                                                           
    "C:\cygwin64\home\Administrator\dumps/MEMORY.DMP" is not a core dump: file format not recognized                                                                

I also tried to convert the crash dump files to minidump format but this didn't work either. 

If the debug helper DLLs support the crash dump format (I assume they do) do you think it is a lot of work to support crash dumps also as core files?

**Comment by ssbssa** [comment]
Looks like system minidumps are very different from user-space minidumps, and not documented at all.
How did you try to convert them?

And I'm not exactly sure how useful it would even be if gdb can read them (but that might be just me, I don't know much about the kernel side of things).

**Comment by johannesthoma** [comment]
Hi, I tried the .dump command of WinDBG. Being able to debug BSOD dumps would allow us to analyze crash dumps we get from clients with the symbols written by gcc.

Background Info: I am working on WinDRBD (https://github.com/LINBIT/windrbd) which is in essence a Linux driver (DRBD) with some (ok a lot ..) gluing code to make the Linux driver work as a native Windows NT driver (the output of the build process is a sys file which can be loaded into the NT kernel). For the new branch we switched from MS VC to gcc because this requires far less patches to the DRBD driver. However windbg does not understand the gcc debug info (as I understood it) and gcc cannot write the MS PDB (programm database) files since that format is closed source. So if I get a crash dump from the field it would be helpful to be able to analyze it with gdb.

Is there a Windows DLL that understands the kernel crash dump format? Does the dgbhelper.dll understand that format?

**Comment by ssbssa** [comment]
So you compile a windows driver with gcc?
That's interesting, I didn't know that was possible, and explains why it would be useful for gdb to understand kernel dumps.

Maybe lldb can handle that?
dbgeng.dll might be able to understand that format, since (I think) that's what WinDBG also uses.

Having said all that, I a a bit curious if I could get gdb to handle kernel dumps, do you maybe have an example dump where a gcc compiled driver is involved (plus the sys file and debug info)?

**Comment by johannesthoma** [comment]
Hi,

I've created a Windows (Server 2019) crashdump file and am sending it via
WeTransfer (is 75MB 25 MB is github limit).

it also contains the windrbd.sys (compiled with gcc and debug info on) and
a screenshot of the windbg session analyzing the stack backtrace.

The source for WinDRBD (for this version) is here:

    git clone --branch windrbd-1.2 --recursive https://github.com/LINBIT/windrbd.git

I found that objdump can dump line number info (but objdump -S does not work):

    objdump --dwarf=decodedline windrbd.sys

With that info I was able to identify the source lines. But nevertheless if gdb would
support Windows kernel crash dumps that would be *awesome* ... :)

**Comment by johannesthoma** [comment]
(just to let you know I found your eMail address in git commits for the WeTransfer, hope that is ok...)

**Comment by ssbssa** [comment]
I made a simple test with heob+dwarfstack to see if I could convert the windrbd callstack addresses (minus 1) from windbg to source lines, which seems to work:
```
heob64.exe -F1 -"windrbd.sys"0xfffff80258670000 0xfffff802586e0f09 0xfffff802586efa71 0xfffff802586f014d

trace:
    0xFFFFF80258670000   C:\gdb\kernel-dump\for-ssa-ssb\windrbd.sys
      0xFFFFF802586E0F09   C:\windrbd\windrbd\src\windrbd_test.c:1303:2 [rtl_zero_memory_test]
                           C:\windrbd\windrbd\src\windrbd_test.c:1422:3 [test_main]
      0xFFFFF802586EFA71   C:\windrbd\windrbd\src\windrbd_device.c:462:4 [windrbd_root_device_control]
                           C:\windrbd\windrbd\src\windrbd_device.c:575:10 [windrbd_device_control]
      0xFFFFF802586F014D   C:\windrbd\windrbd\src\windrbd_device.c:3935:8 [windrbd_dispatch]
```
So you basically got me hooked already, and I'll probably play around with this over the weekend to see if I can understand this dump format.

**Comment by ssbssa** [comment]
I found [parse_minidump.py](https://github.com/larytet/parse_minidump) and thought it had the information necessary to understand kernel dumps, but it doesn't work for your attached dump file at all.
So it looks like I won't be able to implement this for gdb after all.

**Comment by johannesthoma** [comment]
Hi, There seem to be several types of dumps, I am attaching one that is called a 'small memory dump' also referred to as minidump. Could you please check if you can read this format?
[030424-86203-01.dmp](https://github.com/ssbssa/gdb/files/14482310/030424-86203-01.dmp)
(it should display intentionally_bsod as windrbd.sys function).

Thanks a lot for looking into this :) 

- Johannes

**Comment by johannesthoma** [comment]
Hi,

I tried the parse_minidump.py utility you've mentioned and it looks like it can read the file at least partially:

```
johannes@jt-ubuntu2021B:~/parse_minidump$ ./parse_minidump.py parse --filein=030424-86203-01.dmp --debuglevel=100
DEBUG:parser:Parse file '030424-86203-01.dmp'
DEBUG:parser:0x0:Signature = 45474150 (PAGE)
DEBUG:parser:0x4:ValidDump = 34365544 (DU64)
DEBUG:parser:64bits dump
DEBUG:parser:0x8:MajorVersion = 0000000f
DEBUG:parser:0xc:MinorVersion = 00004563 (cE..)
DEBUG:parser:0x10:DirectoryTableBase = 000000013bc30000 (...;....)
DEBUG:parser:0x18:PfnDataBase = ffff950000000000
DEBUG:parser:0x20:PsLoadedModuleList = fffff80410e3a610
DEBUG:parser:0x28:PsActiveProcessHead = fffff80410e2e520 ( .......)
DEBUG:parser:0x30:MachineImageType = 00008664 (d...)
DEBUG:parser:0x34:NumberProcessors = 00000004
DEBUG:parser:0x38:BugCheckCode = deaddead
DEBUG:parser:0x3c:Unknown = 45474150 (PAGE)
DEBUG:parser:0x40:BugCheckParameter = 0000000000000007000000000000001c0000000000000043000000000000002a (*.......C.......................)
DEBUG:parser:Skip 32 bytes
DEBUG:parser:0x80:KdDebuggerDataBlock = fffff80410e1e5e0
DEBUG:parser:0x88:NumberOfRuns = 0000000000000005
DEBUG:parser:0x90:NumberOfPages = 000000000017fed7
DEBUG:parser:0x98:ContextRecord = 00000000000000020000000000000100000000000000009e0000000000000001
DEBUG:parser:0xc50:ExceptionCode = 45474150 (PAGE)
DEBUG:parser:0xc54:ExceptionFlags = 45474150 (PAGE)
DEBUG:parser:0xc58:ExceptionRecord = 4547415045474150 (PAGEPAGE)
DEBUG:parser:0xc60:ExceptionAddress = 4547415045474150 (PAGEPAGE)
DEBUG:parser:0xc68:NumberParameters = 45474150 (PAGE)
DEBUG:parser:0xc6c:__unusedAlignment = 45474150 (PAGE)
DEBUG:parser:0xc70:ExceptionInformation = 4547415045474150454741504547415045474150454741504547415045474150 (PAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGE)
DEBUG:parser:Exception: code=0x45474150, address=0x4547415045474150, flags=0x45474150
DEBUG:parser:0xce8:DumpType = 4547415045474150 (PAGEPAGE)
DEBUG:parser:0xcf0:RequiredDumpSpace = 4547415045474150 (PAGEPAGE)
DEBUG:parser:0xcf8:SystemTime = 4547415045474150 (PAGEPAGE)
DEBUG:parser:0xd00:Comment = 4547415045474150454741504547415045474150454741504547415045474150 (PAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGE)
DEBUG:parser:0xd80:SystemUpTime = 4547415045474150 (PAGEPAGE)
DEBUG:parser:0xd88:MiniDumpFields = 45474150 (PAGE)
DEBUG:parser:0xd8c:SecondaryDataState = 45474150 (PAGE)
DEBUG:parser:0xd90:ProductType = 45474150 (PAGE)
DEBUG:parser:0xd94:WriterStatus = 45474150 (PAGE)
DEBUG:parser:0xd98:Unused1 = 50 (P)
DEBUG:parser:0xd99:KdSecondaryVersion = 41 (A)
DEBUG:parser:0xd9a:Unused2 = 4547 (GE)
DEBUG:parser:0xd9c:Reserved = 4547415045474150454741504547415045474150454741504547415045474150 (PAGEPAGEPAGEPAGEPAGEPAGEPAGEPAGE)
DEBUG:parser:0x1d50:Uknwn = 45474150 (PAGE)
DEBUG:parser:0x1d54:DumbBlob = 45474150 (PAGE)
DEBUG:parser:0x1d58:Uknwn = 45474150 (PAGE)
DEBUG:parser:0x1d5c:StackRva = 45474150 (PAGE)
DEBUG:parser:Stack frames at offset 0x45474150
DEBUG:parser:0x1d60:Uknwn = 45474150 (PAGE)
DEBUG:parser:0x1d64:Uknwn = 45474150 (PAGE)
DEBUG:parser:0x1d68:Uknwn = 45474150 (PAGE)
DEBUG:parser:0x1d6c:Uknwn = 45474150 (PAGE)
DEBUG:parser:0x1d70:Uknwn = 45474150 (PAGE)
DEBUG:parser:0x1d74:Uknwn = 45474150 (PAGE)
DEBUG:parser:0x1d78:Uknwn = 45474150 (PAGE)
DEBUG:parser:0x1d7c:Uknwn = 45474150 (PAGE)
DEBUG:parser:0x1d80:LoadedModules = 45474150 (PAGE)
DEBUG:parser:Loaded modules at offset 0x45474150
DEBUG:parser:0x1d84:Uknwn = 45474150 (PAGE)
DEBUG:parser:0x1d88:StringsRva = 45474150 (PAGE)
DEBUG:parser:Loaded modules names at offset 0x45474150
Traceback (most recent call last):
  File "./parse_minidump.py", line 798, in <module>
    (dump_type_64, physical_memory_presents, stack_frames, exception) = parse_dump(arguments)
  File "./parse_minidump.py", line 776, in parse_dump
    (dump_type_64, physical_memory_presents, stack_frames, exception) = parse_dump_header(arguments, file_dump)
  File "./parse_minidump.py", line 755, in parse_dump_header
    (physical_memory_presents, stack_frames, exception) = parse_dump_header_64(arguments, file_dump)
  File "./parse_minidump.py", line 683, in parse_dump_header_64
    loaded_modules_names = parse_strings(arguments, file_dump, strings_offset)
  File "./parse_minidump.py", line 561, in parse_strings
    length = int(length_hex, 16)
ValueError: invalid literal for int() with base 16: ''
```

The BugCheck codes are correctly parsed.

**Comment by ssbssa** [comment]
Yes, but it fails at the most interesting part of the python script, the module list.

**Comment by johannesthoma** [comment]
Hi, I ran the parse_minidump.py over the large MEMORY.DMP and it cannot handle this format at all. So I guess we should go with the 'minidump' (small memory dump). I think that the python script is incomplete at some point. I found this issue: https://github.com/larytet/parse_minidump/issues/1 which looks exactly like what we are facing. 

If I manage somehow to parse the small memory dump with the python script, would that help implementing support for it in gdb? May take a while, however I think this can be done.

**Comment by ssbssa** [comment]
I think the 'small' memory dump has the same issues, as far as I can tell it uses the same format, but probably just dumps the most important memory locations.

**Comment by johannesthoma** [comment]
Hi, I found:

http://formats.kaitai.io/windows_minidump/

Do you know this site? Are we talking about this format?

**Comment by ssbssa** [comment]
No, but at a quick glance this just document the 'normal' minidumps gdb already knows, not the 'kernel' minidumps this ticket is about.

Edit: you just need to check the first 4 bytes of the minidump file, if it's 'PAGE', it's the kernel minidump format.

**Comment by johannesthoma** [comment]
Ok, thanks for letting me know. I will get back to you when I found a way to parse the 'small memory dumps'. I think this can be done, however this may take some time (working on several other projects as well).

Thanks for your efforts and patience again :)

**Comment by ssbssa** [comment]
I'm closing this, since I currently don't know how those kernel dumps work.
Feel free to reopen if you find out how to parse them.

**Comment by johannesthoma** [comment]
Ok, thanks a lot, I will get back when I decoded the dump file. I was thinking about writing some
small C program which then maybe can be used in the gdb source as well...
